### ISSUE TITLE
Шлема в РИГах не защищают от сварки

### ISSUE THREAD

**Issue by WallShrabnic** [GammaStation/Gamma-Station#106]
#### Подробное описание проблемы
Шлема в РИГах перестали защищать от сварки
#### Что должно было произойти
Шахтёры и прочие инженеры могли в случае чего свободно варить в космосе сваркой стены, РИГИ и прочее 
#### Что произошло на самом деле
Your eyes burn.
#### Как повторить
Варить в космосе
#### Дополнительная информация:
Куршан, ты ебан

**Comment by DieSiege** [comment]
#114
