### ISSUE TITLE
Ян дюпает наручники через резист 

### ISSUE THREAD

**Issue by Hakasolo** [GammaStation/Gamma-Station#107]
#### Подробное описание проблемы
Когда снимаешь наручники через резист, они как бы снимаются, но копия остается на шее. 
#### Что должно было произойти
Они должны нормально сниматься, не оставляя копии на шее псины. 
#### Что произошло на самом деле
Наручники остаются на шее, но дюпается копия. 
#### Как повторить
Попробовать снять наручники за Яна. 
#### Дополнительная информация:
Баг нашел Rev.

**Comment by Moggilazz** [comment]
Оно точно имеет место? Тесты на локалке не выявили данной проблемы

**Comment by Miracler112** [comment]
Видимо это уже поправили со временем, пока шатали всё остальное
