### ISSUE TITLE
[Proposal] Убавить бы звук шлюзов

### ISSUE THREAD

**Issue by Hakasolo** [GammaStation/Gamma-Station#113]
#### Подробное описание проблемы
Звуки шлюзов сравнительно с остальными  слишком мощные. Поэтому иной раз трудно играть с нормальной громкостью, ибо через пять минут от этих *ПШШШШ* начинает идти пена изо рта. 
#### Что должно было произойти
Звук шлюзов не должен выделяться по громкости среди других. 
#### Что произошло на самом деле
Пиздец. 
#### Как повторить
Открой шлюз. 
#### Дополнительная информация:
Перенес предложение с гита классики.

**Comment by Moggilazz** [comment]
Дубликат
