### ISSUE TITLE
Датумы крови - хирургия.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [GammaStation/Gamma-Station#130]
#### Подробное описание проблемы

Датумы крови накладываются некорректно, СПУ и Дионы получают кровь того, кто их резал.

#### Что должно было произойти

У скреллов при надрезе течь фиолетовая кровь, у СПУ - масло, у дион - берёзовый сок.

#### Что произошло на самом деле

У всех троих православная, красная кровь на теле(если их резал православный хирург-человек).

#### Как повторить

Резать СПУ, Скреллов, Дион - хирургом-человеком.

#### Дополнительная информация:

Живительные костыли не спасли нас.

**Comment by Moggilazz** [comment]
Как показало расследование, это ни разу не проблема датумов крови и костыли работают как надо - проблема лежит в одних на всех хирургических оверлеях.

**Comment by LudwigVonChesterfield** [comment]
Шутка именно не в оверлеях, а в том что руки и тело резанного, как и руки хирурга получают кровь не пациента, а того кто оперирует

**Comment by Moggilazz** [comment]
![tau ceti station 2018-12-21 133710](https://user-images.githubusercontent.com/3964933/50326577-1a522d00-0526-11e9-9f44-bc75302eb6e8.png)

Уточни? Вот порезал куклу - на ней нету кровищи, кроме хирургических оверлеев -

**Comment by Moggilazz** [comment]
#641
