### ISSUE TITLE
Шлем обыкновенного мягкого скафандра не защищает от сварки.

### ISSUE THREAD

**Issue by Skippeer12** [GammaStation/Gamma-Station#142]
#### Подробное описание проблемы
Шлем обыкновенного мягкого скафандра не защищает от сварки. Хотя у него вроде как есть даже спрайт затонированого стекла.
#### Что должно было произойти
Сварка никак не должна влиять на работу в этом скафандре.
#### Что произошло на самом деле
ЙОР АЙЗ БЁРНИНГ
#### Как повторить
Взять беленький скафандр из ЕВА
#### Дополнительная информация:
#КуршанПочини

**Comment by DieSiege** [comment]
#114
