### ISSUE TITLE
Проникновение на велосити\ЦК\ЕРТ с помощью ручного телепорта

### ISSUE THREAD

**Issue by Breyn78** [GammaStation/Gamma-Station#189]
#### Подробное описание проблемы
Возможно телепортироваться на велосити сквозь стену и угнав шатл попасть на ЦК, далее к ЕРТ и его мехам\подам ну и соответственно обокрасть это всё.
#### Что должно было произойти
Судя по лору туда нельзя телепортироваться так как у них имеются щиты предотвращающие это 
#### Что произошло на самом деле
Попасть можно с исхода настроив станционный телепорт на маяки и принеся их на велосити\цк
#### Как повторить
Нужно настроить телепорт на спутник ИИ, телепортироваться и забрать маяк, второй не важно куда, телепортироваться и так же забрать маяк, сесть на шатл до велосити и дождаться пока кто-то его вызовет, вскрыть дверь в вагончике на монорельсе, пройти дальше и в комнате со столом положить маяк вплотную к стенке, вернуться на станцию и телепортироваться на этот маяк(возможно не с первого раза выйдет) таким образом можно попасть за стену и угнать шатл велосити... На шатле долетаем до цк, вскрываем двери, берём карту с фул доступом ЦК, поднимаемся наверх где переход в комнату ЕРТ и там невидимая стена, ставим второй маяк вплотную к стене, возвращаемся на исход и повторяем процедуру телепортации как на велосити, таким образом попадаем к ЕРТ, так же можно попасть даже к закрытым дроп подам, второй вариант: оказавшись на цк вскрываем окна, вылетаем в космос в риге и просто долетаем до базы ЕРТ, так можно пробраться без телепорта но с ригом. Так-же с базы ЕРТ можно через космос пробраться к мехам взорвав створки их пусковой установки, итог - весь цк и базу ЕРТ можно обчистить, мехов можно угнать.

**Comment by WallShrabnic** [comment]
С помощью ручного телепорта

 абуз маяка и стационарного телепорта
