### ISSUE TITLE
В трэкинк бикон не работает микрофон.

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#198]
#### Подробное описание проблемы
В Tracking Beacon при включении микрофона через него можно говорить только :r ,что однако я не ожидал, в отличии от портативной жёлтой (я не расист) рации которая работает при переключении микрофона.
![image](https://user-images.githubusercontent.com/36476150/45553490-42166280-b85e-11e8-9b48-a2568a44b10d.png)

#### Что должно было произойти
![image](https://user-images.githubusercontent.com/36476150/45553584-8ace1b80-b85e-11e8-82bf-bd56a5b64e20.png)
Git Hubber [145.9] says, "Кэп портал ставь"

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/36476150/45553584-8ace1b80-b85e-11e8-82bf-bd56a5b64e20.png)
_Git Hubber says, "Кэп портал ставь"_
Git Hubber says, "Чёрт связи нету что ли?"

#### Как повторить
**Tracking Beacon**
Microphone: **Engaged**
Speaker: Engaged

**Comment by Moggilazz** [comment]
Вообще-то, маячок и не должен работать как рация

**Comment by SanecMan** [comment]
Маяк в руку + :r Вася как дела

**Comment by Moggilazz** [comment]
Перефразирую: у него не должно вообще этого окна с микрофоном быть

**Comment by SanecMan** [comment]
Ну тогда IDK,удаляйте микро и динамик,только частоту оставьте.
