### ISSUE TITLE
Невозможность продолжить операцию после ошибки

### ISSUE THREAD

**Issue by Momsek** [GammaStation/Gamma-Station#206]
#### Подробное описание проблемы
Если во время операции на мозге, если сделать ошибку во время действия зажимом, продолжить операцию будет невозможно т.к. ты просто будешь бить персонажа
#### Что должно было произойти
Ты ошибся, повторил действие и продолжил операцию
#### Что произошло на самом деле
Ты ошибся, операцию продолжить никак, у пациента открыта голова
#### Как повторить
Делаем операцию на мозге по исправлению гематом, на моменте дейсвия зажимом отойдите вниз или вверх

**Comment by StrikS** [comment]
Когда у тебя рука срывается, то возникает кровотечение(высокий шанс).
Чтобы продолжить выполнять операцию просто останови его гемостатом.

**Comment by Miracler112** [comment]
Старый ишью. И да, это не баг, операцию можно продолжить с того места, с которого закончил, если через hermostat(зажим) остановить кровь
