### ISSUE TITLE
[Feedback] Зомби режим и почему он сырой.

### ISSUE THREAD

**Issue by Skippeer12** [GammaStation/Gamma-Station#217]
1. Режим не сбалансирован для игры, вообще.
* Зомби получаются очень быстрые, по скорости такие же как и носитель вируса, тоесть если заразили таяру, она переловит всех хуманов, ящеров и других. А если заразили ящера, то он даже хумана догнать не сможет.
* У зомбей нет никакой защиты, только если носитель имел броню, они умирают от двух пулек из летального пистолета в лицо, так же как и хуман.
* У когтей зомби есть очень большой минус, они имеют очень слабый урон, а именно 10 единиц,  тоесть как у балона, этим дамагом даже не пробить цельное стекло.
* Заражение никак не отображаются на ручном сканере или мед.худах. Единственный верный способ узнать болен ли человек, это тащить его в бодисканер.
* Заболтированые и завареные двери никак не открыть, хотя зомби должны это уметь и чтобы это не ломало баланс, сделать этот процесс очень долгим.
* У зомбей есть внутренние органы, хотя это даже не минус а плюс, но из-за того что и кости у них ломаются, они страдают нещадно, ломаются внутренние органы = зомби умирает от них или получает очень страшные дебафы к скорости и отличный геймплей мертвеца на минут 20 пока ему не отпилят голову. Кости и органы не чинятся после воскрешения.
![image](https://user-images.githubusercontent.com/18488106/45849800-2b7b7a00-bd3c-11e8-90ab-f6724537b664.png)
* Уже зараженых и превращеных в зомби никак не спасти и не вылечить, даже если у тебя есть анти-тела. (Не затирайте про фильми, мы играем в игру)
2.  Очень критический баг, которым можно сломать баланс ещё больше и ингейм его не починить.
* Можно надюпать себе когтей зомби, предварительно положив их в ящик
![image](https://user-images.githubusercontent.com/18488106/45849534-f4589900-bd3a-11e8-9031-9c150959322b.png)
После чего любой желающий сможет их взять и начать апокалипсис.
![image](https://user-images.githubusercontent.com/18488106/45849574-18b47580-bd3b-11e8-80ee-a1dc27c3400d.png)

Итог: Смотрите как сделан зомби-режим на маринаде
~~Привет Рассл и Дайсидж~~

**Comment by Skippeer12** [comment]
Nice meme.
![image](https://user-images.githubusercontent.com/18488106/45849978-df7d0500-bd3c-11e8-91b0-d4a7c6a79357.png)

**Comment by DieSiege** [comment]
#220
