### ISSUE TITLE
Не снимаются предметы с новых шлемов

### ISSUE THREAD

**Issue by DieSiege** [GammaStation/Gamma-Station#232]
#### Подробное описание проблемы
Нельзя снять предметы с новых шлемов
#### Что должно было произойти
По нажатию remove item должен был сняться предмет
#### Что произошло на самом деле
Он не снялся
#### Как повторить
Надеть шлем, засунуть в него что-нибудь и попытаться снять
#### Дополнительная информация:
Филат, бери вилку и фикси-фикси-фикси

**Comment by LudwigVonChesterfield** [comment]
#230

**Comment by DieSiege** [comment]
Что-то я слеповат стал, н-да.
