### ISSUE TITLE
Банковские мошенники страдают

### ISSUE THREAD

**Issue by UDaV73rus** [GammaStation/Gamma-Station#234]
#### Подробное описание проблемы
В NanoTrasen Automatic Teller Machine не важно что вводишь в поля Account: PIN:, в любом случае попадаешь в аккаунт, чья карта надета. Без карты вовсе не работает.
#### Что должно было произойти
Вхожу в аккаунт банка и управляю им
#### Что произошло на самом деле
Невозможно войти в банк
#### Как повторить
Разослать всем: Паздравляем! Кампания Megacoft Sekurity выбрала вас победетелелем в розыгрыше путёвки на влаженые осторава Тау Киты! Для падтверждения что вы не бот, пришлите номер банкавского щета и ево пин, как толко оператор падтвердит сушествование аккаунта в банккееке, вы получите далнейшыи указанея!
И получить ответы: (Detective), "мой номер 176599 пин 85875"
(Station Engineer), "210880 96270"
Ввести в банкомат.
#### Дополнительная информация:
Я не вор, честно

**Comment by Thirteenalex** [comment]
Так эта же защита
Разве нет?

**Comment by LudwigVonChesterfield** [comment]
У всех карт изначально нулевой уровень защиты. Это не баг.

**Comment by SanecMan** [comment]
В менюшке карт можно выставить защиту,по умолчанию нулевой.

**Comment by LudwigVonChesterfield** [comment]
Спасибо что повторил сказанное.
