### ISSUE TITLE
Сигарета которая не дает свет

### ISSUE THREAD

**Issue by ghost** [GammaStation/Gamma-Station#240]
#### Подробное описание проблемы
Сигарета в темноте не дает НИКАКОГО света.
#### Что должно было произойти
хоть маленький свет
#### Что произошло на самом деле
нету света
#### Как повторить
Зажечь сигарету, пойти в теха.

**Comment by fousol** [comment]
хоть раз сигареты видел хоть а? они тлеют, а не горят. света не должно быть
