### ISSUE TITLE
[Proposal] Убрать гиб при поедании мятки (mint) жирдяем

### ISSUE THREAD

**Issue by Armando-Rodriguez17** [GammaStation/Gamma-Station#250]
#### Платиновый механ, который должны были выпилить еще на классике при КУРСЕ НА РП, но что-то пошло не так.
 Жирдяй ест мятку и гибается. Гиба быть не должно, либо выпилить данный механ, либо изменить на что-то менее дебильное и брейнротное. Механ с гибом мятой можно использовать для различного грифа, описывать который не стоит, так как гит просматривают многие _механообузиры_.

**Comment by WatlerJe** [comment]
https://youtu.be/GxRnenQYG7I?t=305

РП-Дети не должны губить годные отсылки к Монти Пайтону.

**Comment by Miracler112** [comment]
Пропосал старый + не удался он, никто не будет убирать дедовскую отсылку с мяткой. Решение давно всем принято, но он не прикрыт по сей день, ух
