### ISSUE TITLE
Эмоджи не работают в ПДА

### ISSUE THREAD

**Issue by ghost** [GammaStation/Gamma-Station#261]
#### Подробное описание проблемы
Пишешь эмоджи в ПДА, а картинки не отображаются ВСЕГДА
#### Что должно было произойти
Пепе должна была появится
#### Что произошло на самом деле
Пепе не появилась, появился :pepe:
#### Как повторить
Отправить кому нибудь смайл на ПДА
#### Дополнительная информация:
запер что ты наделал

**Comment by Zap-zapper** [comment]
Не ишью. Я должен был вырезать все пеки из ИЦ.

**Comment by TungstenOctopus** [comment]
Нет, пеки в ПДа уместны

**Comment by TEXH4Pb** [comment]
Пеки в пда всё ещё остаются ООС хуйнёй, хоть и уместны по механу, имхо.
