### ISSUE TITLE
Быть свободным на шаттле == сидеть там в наручниках

### ISSUE THREAD

**Issue by realwoopee** [GammaStation/Gamma-Station#267]
#### Подробное описание проблемы
Трейтор, покидающий станцию на шаттле может быть закован в наручники, но если он не находится в отсеке СБ, то его засчитывает как успешно сбежавшего.
#### Что должно было произойти
Трейтора заковали в наручники на шаттле и не поместили в отсек СБ, и он провалил своё задание "Escape on the shuttle or an escape pod alive and free."
#### Что произошло на самом деле
Трейтора заковали в наручники на шаттле и не поместили в отсек СБ, и он выполнил своё задание "Escape on the shuttle or an escape pod alive and free."
#### Как повторить
Заковать трейтера в наручники на шаттле отбытия/эвауации и оставить в общем отсеке.
#### Дополнительная информация:

**Comment by Flankir** [comment]
Это не баг. Наручники еще не значат что он не на свободе. Может он просто извращенец.

**Comment by realwoopee** [comment]
Окей, спасибо.
