### ISSUE TITLE
[Proposal] Альтернатива будущему спрайту формы СБ 

### ISSUE THREAD

**Issue by EvilCoffe** [GammaStation/Gamma-Station#278]
Так как мне категорически не нравиться новый спрайт формы СБ, решил запилить свой. Цвета сделать помягче, вырвеглазное золото предлагаю заменить на серебро. Так станет на много лучше.
![bandicam 2018-10-08 00-46-00-749](https://user-images.githubusercontent.com/40903038/46587401-a232aa00-ca94-11e8-8ba0-fcd7cc81e640.jpg)

**Comment by TungstenOctopus** [comment]
скрины из игры показывай сразу, так понять как оно выглядит для неопытного глаза решительно невозможно.

**Comment by EvilCoffe** [comment]
Почему-то не получается скомпилировать, пишет мол не находит файл. Как решать проблему ?
code\modules\clothing\clothing.dm:572:warning: 'icons/mob/uniform.dmi': file found only in .rsc
code\modules\mob\living\carbon\human\update_icons.dm:548:warning: 'icons/mob/uniform.dmi': file found only in .rsc
loading maps\testmap.dmm

**Comment by Kernstall** [comment]
А почему ишью, а не пр? А если руки нет у человека, то будет дырка в костюме?

**Comment by EvilCoffe** [comment]
![bandicam 2018-10-08 16-32-03-860](https://user-images.githubusercontent.com/40903038/46611935-e915b380-cb17-11e8-91ad-e2c14ed7add5.jpg)
![bandicam 2018-10-08 16-32-06-761](https://user-images.githubusercontent.com/40903038/46611943-edda6780-cb17-11e8-8c6a-f578306dea80.jpg)
![bandicam 2018-10-08 16-32-08-950](https://user-images.githubusercontent.com/40903038/46611944-edda6780-cb17-11e8-809b-6f85fc218759.jpg)
![bandicam 2018-10-08 16-32-59-975](https://user-images.githubusercontent.com/40903038/46611945-ee72fe00-cb17-11e8-805c-dbef9ed6cfa7.jpg)
![bandicam 2018-10-08 16-33-02-516](https://user-images.githubusercontent.com/40903038/46611946-ee72fe00-cb17-11e8-8501-91192db64b95.jpg)
![bandicam 2018-10-08 16-33-04-925](https://user-images.githubusercontent.com/40903038/46611947-ee72fe00-cb17-11e8-9962-de17909567fd.jpg)
![bandicam 2018-10-08 16-33-08-025](https://user-images.githubusercontent.com/40903038/46611948-ee72fe00-cb17-11e8-95fc-ba50a75f7fff.jpg)
![bandicam 2018-10-08 16-32-05-172](https://user-images.githubusercontent.com/40903038/46611949-ef0b9480-cb17-11e8-8869-f08f0dbea68c.jpg)

**Comment by TungstenOctopus** [comment]
да, точно лучше того что там

**Comment by EvilCoffe** [comment]
Если у человека не будет руки, то дырки по идеи не должно быть, так как спрайт делался не с нуля, а на основе актуальной формы СБ.  P.S. как снять мут в дискорде ? : p

**Comment by AgRevol** [comment]
@Miracler112 этот можно закрывать

**Comment by Miracler112** [comment]
И правда, оно висти, а форма уже давно есть
