### ISSUE TITLE
Проникновение на поды ЕРТ сквозь стену, без открытия шлюза

### ISSUE THREAD

**Issue by Breyn78** [GammaStation/Gamma-Station#284]
#### Подробное описание проблемы
Возможность проникнуть на поды за ЕРТ без открытия дверей, сквозь стену.
#### Что должно было произойти
Невозможность проникнуть на поды ЕРТ без открытия дверей, сквозь стену.
#### Что произошло на самом деле
Проникновение на поды ЕРТ без открытия дверей, сквозь стену.
#### Как повторить
Выйти с базы ЕРТ в космос, подойти в угол к стенке которая огораживает комнату с подами ЕРТ, появится интерфейс пода и можно сесть в самый крайний сквозь стену, так как радиус открытия его интерфейса около 3-х тайлов
#### Дополнительная информация:
Найдено Breyn578, так же как и лаз на ЦК :peka:

**Comment by Skippeer12** [comment]
Спасибо Куршан. (Главное вовремя скинуть на кого-то свою вину).
