### ISSUE TITLE
Поды сломаны 

### ISSUE THREAD

**Issue by ghost** [GammaStation/Gamma-Station#291]
#### Подробное описание проблемы
Поды когда долетают до цк на самом деле не далетаю до цк и просто останавливаются в космосе и когда выйдешь с них падаешь в космос и умираешь 
#### Что должно было произойти
Поды должны были пристокаваться и можно было бы выйти на цк
#### Что произошло на самом деле
Поды остались в космосе, выйдешь смерть
#### Как повторить
Улететь на поде

**Comment by Skippeer12** [comment]
Не баг, а фича. Они могут прилететь на ЦК с шансом 5% при эвакуации.
То что дверки открываются в космосе это плохо конечно и надо фиксить, но всё же.
