### ISSUE TITLE
Баг с вытаскиванием мозга из MMI

### ISSUE THREAD

**Issue by Ayuska** [GammaStation/Gamma-Station#294]
#### Подробное описание проблемы
Если достать мозг из MMI ,то вам удастся достать "brain" который полностью не функциональный,а MMI все так же будет иметь мозг внутри который тоже не возможно достать,MMI так же полностью теряет свои функции

#### Что должно было произойти
Мозг должен был спокойно достаться из MMI ,чтобы его можно было снова запихнуть в тело и клонировать/реанимировать.
При этом MMI должен после этого быть пустым

#### Что произошло на самом деле
Всунул мозг человека,высунул.
Опа,ты вывел человека из игры абсолютно.
Мозг который ты достал является по функционалу мозгом обезьяны,а мозг который все так же в MMI просто красивый спрайт
#### Как повторить
Сунул мозг
Высунул мозг
У тебя два мозга

**Comment by LudwigVonChesterfield** [comment]
На классике есть ПР который это фиксит.

**Comment by DieSiege** [comment]
@LudwigVonChesterfield, укажешь же ты на него ссылочку?
