### ISSUE TITLE
Борги видят нинж в стелсе 

### ISSUE THREAD

**Issue by WallShrabnic** [GammaStation/Gamma-Station#303]
#### Подробное описание проблемы
См. название
#### Что должно было произойти
Нинжи в стелсе невидимы
#### Что произошло на самом деле
Борги стреляли точно по мне и всегда знали, где я нахожусь
#### Как повторить
Поиграть на нинже
#### Дополнительная информация:
N/A

**Comment by EdlerN** [comment]
ИИ и борги видят сквозь стелс нинж бай дезигн так сказать. Откровенно говоря, странно что ты это только сейчас узнал.
