### ISSUE TITLE
Нинжу можно кормить пока он в шлеме.

### ISSUE THREAD

**Issue by ghost** [GammaStation/Gamma-Station#309]
#### Подробное описание проблемы
Ниндзя имеет шлем который фактически закрывает ему рот, а маску которую можно снять закрывает только глаза, но так получилось, что нинжу можно кормить через этот самый шлем.
#### Что должно было произойти
Нинжу нельзя было бы кормить в шлеме.
#### Что произошло на самом деле
Нинжу можно докормить до ожирения и взять с него броню
#### Как повторить
Поймать ниндзю и кормить.
#### Дополнительная информация:
Те кто это делают должны страдать

**Comment by TEXH4Pb** [comment]
Не баг, а фича.

**Comment by ghost** [comment]
Фичи надо уничтожать. Плохие фичи.
