### ISSUE TITLE
Нельзя положить в альбом фотки

### ISSUE THREAD

**Issue by Mazzik12** [GammaStation/Gamma-Station#323]
Подробное описание проблемы У детектива есть альбом. Делаем фотку и кладем в альбом. Вроде бы логично. Но из-за нового инвентория случился баг, и в альбоме где-то 0 слотов. Спасибо за порт инвентаря
![bug 1](https://user-images.githubusercontent.com/42623478/47604820-65a8fd00-da07-11e8-8700-1e9ff0257712.png)
![bug 2](https://user-images.githubusercontent.com/42623478/47604821-65a8fd00-da07-11e8-807a-0b128b8e2fa0.png)
![bug 3](https://user-images.githubusercontent.com/42623478/47604822-65a8fd00-da07-11e8-97f6-97a3cc10f7e1.png)

**Comment by Thirteenalex** [comment]
Так ещё и с библееё

**Comment by Miracler112** [comment]
Две проблемы, один корень #307
