### ISSUE TITLE
[map] Проблема с картой

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#327]
#### Подробное описание проблемы
1. Реклама не отображается правильно, а отображается как "Object"
2. Дверь в инженерной лишняя
![image](https://user-images.githubusercontent.com/36476150/47607384-8b56f600-da49-11e8-9644-b93bffa51dc6.png)

#### Что должно было произойти
1. Показывается название рекламы нормально
2. Убрана дверь

#### Что произошло на самом деле
1. This tis Object
2. Дверь стоит,МУЛбот тупит

#### Как повторить
1. Найти щит с рекламой и осмотреть его
2. Подойти к выдаче в карго

#### Дополнительная информация:
Багов слишком много.

**Comment by AgRevol** [comment]
@SanecMan о какой рекламе идёт речь?

**Comment by SanecMan** [comment]
@AgRevol в старом баре есть одна. В тех туннелях на юге вторая. Всё что видел.

**Comment by AgRevol** [comment]
@Miracler112 закрывай, да
