### ISSUE TITLE
Шапка то красная

### ISSUE THREAD

**Issue by Thirteenalex** [GammaStation/Gamma-Station#340]
#### Подробное описание проблемы
Красный берет у сержанта
#### Что должно было произойти
Он должен быть синим
#### Что произошло на самом деле
На спрайте хумана, он красный
#### Как повторить
Одеть берет сержанта
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/35332279/47614936-eb38b580-dab8-11e8-987e-5aabe96b7ff4.png)

**Comment by Damirrus1** [comment]
Закройте штоле

**Comment by Miracler112** [comment]
Исправлено
