### ISSUE TITLE
[MAP] Техи под угрозой тотальной разгермы

### ISSUE THREAD

**Issue by Pivo24** [GammaStation/Gamma-Station#352]
#### Подробное описание проблемы
Ребят вы проебали атмосферные тревоги в техтоннелях. Одна дырка в стенке - и тотал разгерма по всем техам гарантирована. Один открытый баллон плазмы = Тотал разгерма по всем техам
#### Что должно было произойти
Закрытие створок, спровоцированное включением атмосферной тревоги
#### Что произошло на самом деле
Пожар по всем техтоннелям/Разгерма по всей станции из-за одного ИИ и одного инжеборга/Утечка форона и смерти по всей станции
#### Как повторить
Берёшь короче с4, и взрываешь стенку в космос. Все, кто находился в тех же техах, что и ты, умирают.

**Comment by Miracler112** [comment]
Ишью не актуальный, всё исправлено
