### ISSUE TITLE
Шкаф СЕ

### ISSUE THREAD

**Issue by PineappleMen** [GammaStation/Gamma-Station#362]
#### Подробное описание проблемы

Со старта раунда в кабинете СЕ нет шкафчика, соответственно нет чертежей и пульта управления дверьми.
* заметил его за цветком, поменяйте месторасположение на нормальное

![image](https://user-images.githubusercontent.com/44688724/47889246-bb145c80-de94-11e8-9cab-4004826d0cfd.png)

**Comment by KiPakr** [comment]
Все нормально со шкафом.

**Comment by Thirteenalex** [comment]
Эта фича

**Comment by AgRevol** [comment]
Можно закрывать
