### ISSUE TITLE
Нет проводки к APC

### ISSUE THREAD

**Issue by PineappleMen** [GammaStation/Gamma-Station#363]
#### Подробное описание проблемы

Не провели проводку к APC бара и Private Office.

![image](https://user-images.githubusercontent.com/44688724/47889330-21997a80-de95-11e8-9d07-3719a29c5d3c.png)
![image](https://user-images.githubusercontent.com/44688724/47889379-66bdac80-de95-11e8-807e-88b7bb40b48e.png)

**Comment by AgRevol** [comment]
Well shit

**Comment by ghost** [comment]
проведи сам

**Comment by AgRevol** [comment]
Уже проведена, да. Можете закрывать
