### ISSUE TITLE
Нельзя протирать стаканы тряпочкой

### ISSUE THREAD

**Issue by AgRevol** [GammaStation/Gamma-Station#390]
#### Подробное описание проблемы
Нельзя протирать стаканы тряпочкой, если они находятся в руке. Разве что ставить на стол и протирать.
![image](https://user-images.githubusercontent.com/29666964/48300457-b0864280-e4e6-11e8-90f0-e6b80dd2df47.png)
#### Что должно было произойти
Стакан протерся и всем написало, какой у них классный бармен.
#### Что произошло на самом деле
You need to take that Drinking glass of before cleaning it.
#### Как повторить
Попробовать протереть стакан тряпочкой, пока он находится в руке.
#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/29666964/48300483-0eb32580-e4e7-11e8-9155-6de78e8db4bf.png)

**Comment by AgRevol** [comment]
Critical bug, literaly unplayable

**Comment by Miracler112** [comment]
Critical bug is fixed comrad

**Comment by AgRevol** [comment]
Playable again, yay
