### ISSUE TITLE
ОБР и их шатл

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#392]
#### Подробное описание проблемы
На шатле ОБР их радио не настроено на частоту ОБРовцев.
На шатле ОБР не работает панель с шлемокамерами.

#### Что должно было произойти
Ты зашёл на шатл ОБРовцев и начал их прослушивать.
Ты можешь глядеть, где эти ОБРовцы шатаются.

#### Что произошло на самом деле
Радио у ОБР на шатле настроено на 144.3 , но не саму частоту ОБР (палить частоту не буду, ищите сами в коде)
Камеры не работают даже если по ним провести картой.

#### Как повторить
Зайти на шатл ОБР.
Зайти на шатл ОБР.

**Comment by AgRevol** [comment]
Камеры, если мне не изменяет память, ОБРовцы должны сами включить на шлеме (кликом по нему)

**Comment by Miracler112** [comment]
Камеры ОБРовцы включать должны сами, так что это не является багом, но частоту пошатать надо, да

**Comment by SanecMan** [comment]
Включал, но на консоли не видно камер (т.е. идёт сканирование карты а потом только можно фонарик включить) . Сравните камеру нюки (шлем) и ОБР (шлем) . У нюки после проводка картой камера работает а у ОБР - нет.

**Comment by Miracler112** [comment]
Проверим тогда
