### ISSUE TITLE
[MAP]На карте не хватает кадила и эктоплазмы.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [GammaStation/Gamma-Station#400]
читай титулку

**Comment by AgRevol** [comment]
Подскажи их пути и где лежало кадило - добавлю

**Comment by LudwigVonChesterfield** [comment]
Кадило лежало на столе у капеллана.

Эктоплазма: /obj/item/weapon/reagent_containers/food/snacks/ectoplasm
Кадило: /obj/item/weapon/reagent_containers/spray/thurible
