### ISSUE TITLE
[MAP]Труба на спутнике ИИ которой нет.

### ISSUE THREAD

**Issue by AndroBetel** [GammaStation/Gamma-Station#401]
#### Подробное описание проблемы
На спутнике ИИ под одним из шлюзов нет трубы для скраббера
![image](https://user-images.githubusercontent.com/44546836/48314605-d5f57800-e5dc-11e8-8302-84df20f16ec1.png)

#### Что должно было произойти
Она там должна быть.

#### Что произошло на самом деле
Ее там нет.

#### Как повторить
Придти, увидеть, уйти.

**Comment by Miracler112** [comment]
Атмосфера там с ума не сходит?

**Comment by AndroBetel** [comment]
> Атмосфера там с ума не сходит?

вроде нет, но за мыш сложно грифонить турели.

**Comment by Miracler112** [comment]
Хорошо
