### ISSUE TITLE
Лоадаут персонажа, Rogue jacket заменяется на Navy suit

### ISSUE THREAD

**Issue by Andagar** [GammaStation/Gamma-Station#424]
#### Подробное описание проблемы
При выборе в лоадауте персонажа костюма Rogue jacket, в самой игре персонаж появляется в костюме Navy suit.

#### Что должно было произойти
Персонаж должен был появиться в Rogue jacket.

#### Что произошло на самом деле
Персонаж появился в Navy suit.

#### Как повторить
В меню выбора костюмов персонажа, выбираем Rogue jacket.
Заходим в раунд.
Получаем Navy suit.

**Comment by Miracler112** [comment]
@TungstenOctopus Ишью на твой ПР
