### ISSUE TITLE
Баллон не помещается в суйт стораж обычного (белого) космического костюма

### ISSUE THREAD

**Issue by torn223** [GammaStation/Gamma-Station#425]
#### Подробное описание проблемы:
Не суется!

#### Что должно было произойти:
Должно было сунуться!

#### Что произошло на самом деле:
Не суется!

#### Как повторить:
Одеть обычный космокостюм, взять баллон с кислородом и попробовать его нацепить

**Comment by Skippeer12** [comment]
Какой балон, какого размера.
Если большой синий, то это фича, если маленький синий, то надо фиксить

**Comment by torn223** [comment]
> Какой балон, какого размера.
> Если большой синий, то это фича, если маленький синий, то надо фиксить

С какой стати стандартный большой баллон не может поместиться на стандартный гражданский космический костюм?

**Comment by ViDLiathan** [comment]
Древние вещи, к которым привыкли и не репортили, становятся фичами?

**Comment by Skippeer12** [comment]
Потому что он большой и крепится только на риги, все мягкие скафандры, кроме научного и мусорщика не имеют этого крепления - это если объяснять со стороны Ролеплейного РП.

А теперь объяснения со стороны баланса - носить большой балон слишком имбовый, чтобы носить его на том же скафандре, хочешь долго дышать с большого балона, носи его на спине.

>Древние вещи, к которым привыкли и не репортили, становятся фичами?

Да, так это и работает.

**Comment by Miracler112** [comment]
Ну, вообще для баланса в гражданские скафандры нельзя поставить большой балон в suit_storage. Они обычно одеваются на спину в таких случаях. Исключение это скафандры шахтеров, мусорщиков и ученых

**Comment by Miracler112** [comment]
А конкретно маленькие одеть туда можно. Ишью закрываю так как не баг
