### ISSUE TITLE
ПоДо_ПрОбЛеМы

### ISSUE THREAD

**Issue by omejka** [GammaStation/Gamma-Station#430]
#### Подробное описание проблемы
Из подов нельзя достать батарейку,в самом поде нельзя посмотреть ее заряд
Оружие с пода не снимается
Поды с Берст-мод-адаптером гибают сами сюда
С-4 при взрыве на поде не меняет спрайт на сломанный
Нельзя делитнуть поды(или они делитаются только через время)
Мэйби мор

**Comment by TEXH4Pb** [comment]
Блять, сейчас бы все баги в один ишью запихнуть.

**Comment by omejka** [comment]
Давай мы наплодим говна
Их все равно закроют скорее всего в одном пре

**Comment by TEXH4Pb** [comment]
Или один из багов не смогут закрыть, и будем держать ишью открытым, пока один из десяти багов не будет пофикшен. Кайф

**Comment by Miracler112** [comment]
#439
