### ISSUE TITLE
Отсутствие спрайта у dirt pack plastellium mycelium

### ISSUE THREAD

**Issue by RedHoll** [GammaStation/Gamma-Station#448]
#### Подробное описание проблемы
У объекта "dirt pack plastellium mycelium" отсутствует спрайт. У других объектов, например у "dirt pack chanterelle mycelium" и подобных спрайты есть.
#### Что должно было произойти
Объект должен был появиться со спрайтом.
#### Что произошло на самом деле
У объекта отсутствует спрайт.
#### Как повторить
Найти "expired crate" в мусоре, внутри которого и будет объект без спрайта "dirt pack plastellium mycelium".

**Comment by RedHoll** [comment]
dirty*
Не могу уже редактировать.

**Comment by AgRevol** [comment]
под dirt подразумевается грязные (dirty/expired) обьекты?

**Comment by RedHoll** [comment]
Да, опечатался, dirty.
