### ISSUE TITLE
[Proposal] Гранатомет на плечо

### ISSUE THREAD

**Issue by WatlerJe** [GammaStation/Gamma-Station#456]
Полицейский гранатомет на три снаряда нельзя таскать на слоте пояса и броника. Тащемта одна из самых полезных вещей при не летальном воздействии на экипаж, но не пользуется популярностью среди охранки.

**Comment by Skippeer12** [comment]
Мне кажется просто спрайта не было для пояса вот и не добавили.

**Comment by WatlerJe** [comment]
Как и большей части пушек. Неубедительно.

**Comment by Skippeer12** [comment]
То есть ты бы носил эту хуйню в таком виде?
![image](https://user-images.githubusercontent.com/18488106/48895400-a997f200-ee4d-11e8-9ee4-cc1f1d7ec9db.png)

Когда она выглядит вот так?
![image](https://user-images.githubusercontent.com/18488106/48895423-b61c4a80-ee4d-11e8-8059-b963934c6a93.png)

Я хоть прям сейчас добавить возможность положить её на пояс, но выглядить оно будет убого

UPD.
Хотя и сейчас её можно носить на поясе.
![image](https://user-images.githubusercontent.com/18488106/48895550-0398b780-ee4e-11e8-883b-d6c677a9be4d.png)

**Comment by WatlerJe** [comment]
Например у лазерной винтовки спрайта на броне и поясе вообще нету, а она летального воздействия. Непонятно чего ты так цепляешься к гранатомету.

Описался выше про пояс, да имеется ввиду что нельзя носить на слоте брони.

**Comment by Skippeer12** [comment]
Не то чтобы цепляюсь, просто это выглядит отвратно.
Может там была какая-то идея за тем что его нельзя положить на слот брони или же просто забыли добавить его туда.

**Comment by WatlerJe** [comment]
Энивэй предложение в силе.

**Comment by Breyn78** [comment]
Готово, теперь всё вешается на броню и спину, было бы конечно неплохо ещё сделать ему нормальный спрайт, и так же отображение в соответствующих слотах, но тут я наверное бессилен, спрайтер кажется вы 😆
