### ISSUE TITLE
[Proposal] Тритор ИИ без радио

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#466]
У тритора ИИ нет доступа к радио синдиката. Взлом платой из аплинка тритора также не даёт радио триторов ИИшке. Нужды так сказать, например коопить с ИИ на отдельном канале.

**Comment by SanecMan** [comment]
Забыл дополнить: Настроить на частоту Нюки [#unkn] незя на вещателе ИИ, как и на рядом находящеися говорители.

**Comment by Miracler112** [comment]
Это отдельная и секретная частота, по идее на неё и нельзя настроится вообще никак, только отдельное оборудование изначально может поддерживать эту частоту и не более

**Comment by SanecMan** [comment]
Знаю, но хочется что бы ИИ тритор имел доступ к этой частоте (ака кооп с татором-хуманом)

**Comment by Miracler112** [comment]
Может быть когда-нибудь реализуют фичу, что бы всякие таторы могли йоло взламывать интеркомы, что бы там можно было и на частоту кастомную подкрутить любую, но это другая история. Пропосал прикрываю, так как верховные директоры сказали нет и еще раз нет
