### ISSUE TITLE
[Proposal] Однообразный VR тандур

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#476]
Если честно, то VR чёто не зашёл, ибо эта однообразная карта, без музыки и с только одними раскидананными баллонами.
### Что бы хотелось увидеть: 
Как минимум карты похожии на карты 3-й кваки .
Рандом пушки
Броня
Иногда спэллы
Боты-убийцы

### Что замержили: 
Однообразная карта
Одни огнетушители
Без брони (Что даёт уже набившим себе кучу очков нехилое преимущество над новичками)
Без спец приёмов
Катоники

**Comment by Filatelele** [comment]
>Минимум три карты
А ты знаешь, что прежде чем пилить новые карты, нужно хотя-бы пофиксить баги, которые вскрылись после обкатки тандера? 
>Рандом пушки
Честно, я не понял что ты хочешь. 
>Иногда спэллы
Кодить будешь ты
>Без музыки
Мне тратить свои деньги на покупку саундтреков или че? Тебе так сложно открыть ютубчик и включить сабатон? 
>Броня
А ее нет в магазине?
>Боты-убийцы
С нашим поведением simple mobов об этом не может быть и речи

>Однообразная карта
Критикуешь - предлагай
>Без спец-приемов
Тьфу, блять. 

Иди играй в рейнбоус сикс сайдж, там все описанное тобой есть. Я закончил.

**Comment by Miracler112** [comment]
Закрываю этот пропосал, так как автор тандера высказал резкий отказ по этому пропосалу
