### ISSUE TITLE
Тандер убивает кэшем бульенд

### ISSUE THREAD

**Issue by UDaV73rus** [GammaStation/Gamma-Station#489]
#### Подробное описание проблемы
Клиент начинает лагать будто пинг под 500, но он стабильно мал. После очистки кэша всё становится отлично.
#### Что должно было произойти
Робастишь-робастишь-робастишь и чувствуешь себя отлично!
#### Что произошло на самом деле
Ты стал тормознутым задротом, хилым, не умеющий в робаст даже вне тандера...
#### Как повторить
Быть ВР-зависимым и часто заходить на тандер в течении 3-4 раундов
#### Дополнительная информация:
Слишком реализм. Унижение задротов в игре с задротами игры!!111!1

**Comment by Miracler112** [comment]
Приоритет "Высокий" так как не у всех оно происходит и возникает только у некоторых

**Comment by Filatelele** [comment]
Не смог повторить. Пытался, пару раундов играл на сервере - никаких фризов не обнаружено.
Видимо, какие-то проблемы с версией бьенда/железом.

**Comment by UDaV73rus** [comment]
Обновил бьенд, ушло

**Comment by Miracler112** [comment]
Значит закрываю, так как всё же не баг. Оставлю сообщение для будущего. Просто обновите бьенд до последней беты и всё будет хорошо
