### ISSUE TITLE
Генокрад на тандере имба

### ISSUE THREAD

**Issue by Momsek** [GammaStation/Gamma-Station#492]
#### Подробное описание проблемы
Генокрад на тандере может высосать гены у любого человека, очки засчитаются, а человек не умрет и зареспавнится
#### Что должно было произойти
Человек не смог быть поглощен/умер бы в реальной жизни
#### Что произошло на самом деле
Генка получила очки, человек жив
#### Как повторить
Заходим на тандер, берем генку и обычного человека, генка высасывает гены из человека
#### Дополнительная информация:
Нету

**Comment by Ayuska** [comment]
Пофиксили же

**Comment by Miracler112** [comment]
Закрываю так как пофикшено
