### ISSUE TITLE
Енергия убивает

### ISSUE THREAD

**Issue by Momsek** [GammaStation/Gamma-Station#493]
#### Подробное описание проблемы
При отключении енергии почти весь персонал умирает. Умирают лишь те, кто был в тандере хоть раз
#### Что должно было произойти
Енергии нету, никто не умер
#### Что произошло на самом деле
Енергии нету, умерли
#### Как повторить
Залезть в тандер, отключить енергию

**Comment by Ayuska** [comment]
Так умирает или нет?
Определись.
