### ISSUE TITLE
Все проблемы Тандера

### ISSUE THREAD

**Issue by Kurshan** [GammaStation/Gamma-Station#500]
#### Подробное описание проблемы
Тупые админы выключили виАр
#### Что должно было произойти
НеТупые админы не должны были выключать виАр
#### Что произошло на самом деле
ВиАр не работает из-за тупых админов тупых админов
#### Как повторить
Провести революцию и через несколько месяцев написать ищью с отсылкой к прошлому
#### Дополнительная информация:
Я идиот, убейте меня, а Тандер включите, да. А я снова в гроб.

Upd. Мне всё ещё похуй и я уже генерал!

**Comment by Thirteenalex** [comment]
Не баг а фича

**Comment by LudwigVonChesterfield** [comment]
Обновил бьёнд, ушло.

**Comment by Filatelele** [comment]
Удалил бьёнд, прошло.

**Comment by Miracler112** [comment]
Тандер снова открыт, ура
