### ISSUE TITLE
Тандерфилдо проблемы.

### ISSUE THREAD

**Issue by ghost** [GammaStation/Gamma-Station#501]
#### Подробное описание проблемы
Когда вырубят энергии тандерфилда, может быть такое, что вас выкинет из капсулы вы пойдете по станции, а когда ее включат вы окажетесь в игре, а ваше тело будет там где вы ходили по станции и остановились.
#### Что должно было произойти
Вас не должно вернуть в игру
#### Что произошло на самом деле
Вы в игре, ваше тело сьели стулокрады
#### Как повторить
Зайти в капсулу, попросить друга отключить энергии, пройтись по станции, включить энергию.

**Comment by Filatelele** [comment]
Я вчера вроде как пофиксил эту проблему. Она все еще есть?

**Comment by ghost** [comment]
Не знаю, тандер закрыли

**Comment by Miracler112** [comment]
Баг пофикшен оказался
