### ISSUE TITLE
Тандерфилд, баг с игровой панелью

### ISSUE THREAD

**Issue by Lizurt** [GammaStation/Gamma-Station#503]
#### Подробное описание проблемы
Панель при закрытии, которая содержит кнопки "Магазин", "Выход" и так далее, все еще кликабельна. То есть, при нажатии на пустое место, где, к примеру, должен быть магазин, открывается панель на которую нажал. Мешает стрельбе, когда враг слева.
#### Что должно было произойти
Панель не должна открываться при нажатии на пустое место
#### Что произошло на самом деле
Она открылась, твоя кукла встала на месте из за того что открылось новое окно
#### Как повторить
Закрыть открытую панель, нажать на пустое место, где примерно должна быть какая то кнопочка.
#### Дополнительная информация:

**Comment by Miracler112** [comment]
Фикс есть, а потому закрываю ишью. Если вдруг этот баг всё равно кто-то словит, то напишите его еще раз или попросите открыть этот ишью снова
