### ISSUE TITLE
У ИИ спал туман войны на космосе и большей части карты Live!

### ISSUE THREAD

**Issue by Kernstall** [GammaStation/Gamma-Station#51]
#### Подробное описание проблемы
![image](https://user-images.githubusercontent.com/16035287/42531077-b38a802e-848b-11e8-9b7a-bedac966f259.png)
![image](https://user-images.githubusercontent.com/16035287/42531157-e552346c-848b-11e8-88d8-7c817c3fd56e.png)
![image](https://user-images.githubusercontent.com/16035287/42531169-f1dc6edc-848b-11e8-9185-256528d7bdbc.png)
Чат скрыл, но ишью написал, потому что могу что-то потестить еще и собрать инфу о баге
На первом пике ученого видно и по нему можно кликать, но джамп на него не происходит, потому что он "вне камер"

#### Что должно было произойти
Этого не должно быть

#### Как повторить
Без понятия, задавайте вопросы, пока я могу что-то потестить. Возможно здесь замешан телесаенс и джамп на ученого

**Comment by Kernstall** [comment]
![image](https://user-images.githubusercontent.com/16035287/42531639-22723788-848d-11e8-978d-b69b55095e87.png)
![image](https://user-images.githubusercontent.com/16035287/42531672-3cd5be6a-848d-11e8-936b-035f131c8373.png)
Рандомный кусок космоса.
Карту короче сломали наверное

**Comment by Kernstall** [comment]
Перезаход не фиксит

**Comment by WallShrabnic** [comment]
Баги беты

**Comment by Moggilazz** [comment]
Я так понял, дело было так - ии отслеживал учёного на камерах, в это время учёный прыгнул в телесайнс и камера прыгнула за ним?

**Comment by Kernstall** [comment]
Нет, видимо это проблема беты.

**Comment by Kernstall** [comment]
Нет, видимо проблемы беты

https://github.com/TauCetiStation/TauCetiClassic/issues/2599
