### ISSUE TITLE
Исход на космокостюмах.

### ISSUE THREAD

**Issue by AndroBetel** [GammaStation/Gamma-Station#515]
#### Подробное описание проблемы
На гражданском спесс сьюте из ЕВЫ в описании написано что он еще с ЕХОДУСА.
That's a space suit.
A suit that protects against low pressure environments. "NSS EXODUS" is written in large block letters on the back.

#### Что должно было произойти
Там должна быть великая ГАММА

#### Что произошло на самом деле
Там какой-то ИСХОД.

#### Как повторить
Украсть костюм и нажать ЕХАМИНЕ.

**Comment by LudwigVonChesterfield** [comment]
Его просто скомуниздили наши корпоративные сотрудники!

**Comment by Breyn78** [comment]
Пофиксил, завтра наверно вечером-ночью выкачу ПР вместе с каким-нибудь ещё фиксом.
