### ISSUE TITLE
Не работает клонирование ископаемых у ксеноархеолога

### ISSUE THREAD

**Issue by blind0** [GammaStation/Gamma-Station#532]
#### Подробное описание проблемы
Переодически ксеноархеолог находит непонятные ракушки, их по механу можно засунуть в консоль клонпода,которую можно найти у ксенобиолога, расставить гены в нужном порядке и получить неведомое нечто из клонпода, но когда суёшь ископаемое в консоль и пытаешься расставить гены, генов в списке попросту нету.
#### Что должно было произойти
должна была быть возможность расставить гены ископаемого и получить домашнего зомбе
#### Что произошло на самом деле
при засосывании ископаемого не появились гены, следственно не появился домашний зомбе
#### Как повторить
взять ископаемое, засунуть в консоль клонпода у ксенобиолога и попытаться расставить гены.

**Comment by RichardJones1** [comment]
Всё должно работать, просто для него нужно овердохрена генов. Сколько ты пробовал? Если вообще не появляется, то вы явно что-то сломали. На классике я бафнул консоль кстати сильно, а то собирать гены очень уж долго было.

**Comment by blind0** [comment]
> Всё должно работать, просто для него нужно овердохрена генов. Сколько ты пробовал? Если вообще не появляется, то вы явно что-то сломали. На классике я бафнул консоль кстати сильно, а то собирать гены очень уж долго было.

я пробовал один раз, но генов не было прям вообще, была возможность их расставить, но самих генов не было.

**Comment by RichardJones1** [comment]
Оно так и работает. В ископаемом может содержаться даже несколько генов, а может новая схема существа - тот самый горизонтальный список куда можно расставить гены. Ишью можно закрывать.

**Comment by Miracler112** [comment]
Так если была возможность расставлять, то в чем проблема? Оно так и должно работать

**Comment by Miracler112** [comment]
Ишью закрываю, так как всё нормально

**Comment by RichardJones1** [comment]
Он засунул ископаемое, но в консоли лишь появилась строчка, в которой расставлять гены, но ни одного гена.
Это не баг, оно так работает, просто нужна тонна ископаемых.
