### ISSUE TITLE
Сломал инкубатор в вирусологии

### ISSUE THREAD

**Issue by KuzyXD-zz** [GammaStation/Gamma-Station#55]
#### Подробное описание проблемы
Начал добавлять токсичности до 50 в инкубатор, оставалось мало еды. Тем временем у меня который раз сканировался образец. Сунул его в инкубатор во время насыщение токсинами, усе, вирус он не видит, но dish есть.
#### Что должно было произойти
Вирус должен был идентифицироваться.
#### Что произошло на самом деле
Меня показали средний палец, а dish-то был последним.
#### Как повторить
50+ токсичности и почти под ноль еды.

**Comment by KuzyXD-zz** [comment]
https://c2n.me/3VrwoTt

**Comment by Miracler112** [comment]
#102
