### ISSUE TITLE
Двери клятые двери

### ISSUE THREAD

**Issue by Thirteenalex** [GammaStation/Gamma-Station#552]
#### Подробное описание проблемы
Сломались доступы у бармена и библиотекаря, конкретно стеклянные
#### Что должно было произойти
Они должны открываться 
#### Что произошло на самом деле
Они не открылись
#### Как повторить
Попробовать открыть за библиотекаря стеклянную дверь у него в офисе
#### Дополнительная информация:
Возможно где-то ещё я не проверял

**Comment by LudwigVonChesterfield** [comment]
Это произошло когда?
