### ISSUE TITLE
Одеваемся с помощью телекинеза

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#565]
#### Подробное описание проблемы
С помощью телекинеза на расстоянии можно надеть РИГ

#### Что должно было произойти
Незя на расстоянии надевать РИГ

#### Что произошло на самом деле

![image](https://user-images.githubusercontent.com/36476150/49389455-ebcc0800-f758-11e8-96c8-f12cc1924234.png)

![image](https://user-images.githubusercontent.com/36476150/49389467-f4244300-f758-11e8-9ac4-796424935d50.png)

#### Как повторить
С помощью телекинеза взять в граб РИГ и одеть его

#### Дополнительная информация:

![image](https://user-images.githubusercontent.com/36476150/49389520-203fc400-f759-11e8-807d-cb87bb073df1.png)

**Comment by LudwigVonChesterfield** [comment]
не понял. проблема что он наделся через стекло?

**Comment by SanecMan** [comment]
Ещё можно вертеть шлем, который уже одет с помощью телекинеза на голове

![image](https://user-images.githubusercontent.com/36476150/49389562-33529400-f759-11e8-8e67-0ab13b48ea35.png)

**Comment by LudwigVonChesterfield** [comment]
верчение это топ фича, а не баг.

**Comment by SanecMan** [comment]
Ща по скринам поясню

**Comment by SanecMan** [comment]
DanСегодня в 00:12
@SanecMan в чём баг с ригом
он надевается сквозь преграды?
SanecManСегодня в 00:13
Да

![image](https://user-images.githubusercontent.com/36476150/49389670-77de2f80-f759-11e8-8fa8-2bc0d700b0f0.png)

![image](https://user-images.githubusercontent.com/36476150/49389704-888ea580-f759-11e8-844e-0ddf319c9dd0.png)

**Comment by Miracler112** [comment]
@LudwigVonChesterfield Я так понимаю проблема в том, что на себя можно одеть любые вещи через любые преграды на расстоянии в 100500км от себя

**Comment by SanecMan** [comment]
@LudwigVonChesterfield ещё можно фотографировать себя с помощью телекинеза

![image](https://user-images.githubusercontent.com/36476150/49390099-8da02480-f75a-11e8-84eb-d9e0790c65e5.png)
