### ISSUE TITLE
Телекинез и оружие

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#572]
#### Подробное описание проблемы
Многие предметы можно брать через стекло к себе в сумку.

#### Что должно было произойти
Так не должно.

#### Что произошло на самом деле

![image](https://user-images.githubusercontent.com/36476150/49429045-245ff600-f7da-11e8-92f2-8cd6707e7ee4.png)

![image](https://user-images.githubusercontent.com/36476150/49429068-32157b80-f7da-11e8-813d-78600037ac2b.png)

#### Как повторить
Телепатию в хумана - Грабаем предмет телепатией через стекло и кладём предмет в сумку

**Comment by Miracler112** [comment]
@LudwigVonChesterfield Как помню тот твой ПР фиксил только одевания на себя вещей, теперь это подкатило
