### ISSUE TITLE
Скрипты телекоммуникации не работают

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#583]
#### Подробное описание проблемы
Через эту зелёную консоль незльзя вводить скрипты для телекомов.

#### Что должно было произойти
Its OK.

#### Что произошло на самом деле
Консоли не кликабельны.

#### Как повторить
Тыкнуть по телеком. консоли (та что зелёная)

#### Дополнительная информация:
https://youtu.be/mUeaMDD8Cmc?t=252

**Comment by Skippeer12** [comment]
Их специально отключили из-за плохого кода телекоммов

**Comment by SanecMan** [comment]
Ну так включите обратно, как я буду то троллить егроков показывая им вместо привычного `Mr Freeman [145.9] says: "Где тесла?"` чтото типа `Tritor [145.9] says: "Чё за хуйня со связью? Почему я говорю в рацию будто не своим голосом?"`

**Comment by Skippeer12** [comment]
А теперь прочитай мое предыдущее сообщение внимательно.

**Comment by SanecMan** [comment]
Ну тогда налаживайте код, если он плохой.

**Comment by Breyn78** [comment]
годная штука, я бы так поигрался, а с какого билда видос? мб оттуда утащить чего можно, ибо увидал прикольную фичу - при вызове шатла можно ещё и сообщение типо анонса туда вписать

**Comment by SanecMan** [comment]
> годная штука, я бы так поигрался, а с какого билда видос? мб оттуда утащить чего можно, ибо увидал прикольную фичу - при вызове шатла можно ещё и сообщение типо анонса туда вписать

@Breyn78 вроде ТГ . Штука прикольная, но вот то что её убрали - нет .

**Comment by Filatelele** [comment]
![ecab26e8-8b36-4f9a-a8f0-0d014e0b722f](https://user-images.githubusercontent.com/23741266/49504492-d48d3780-f88a-11e8-83ba-53ca88f2843e.png)

This ^

Предлагаю закрыть пропозал, смысла пратктического нет.

**Comment by Miracler112** [comment]
Закрываю этот ишью, так как скрипты выпилены давным давном, а что бы их воспроизвести снова нужен либо грамотный порт, либо монстр, который сможет их написать нормально и так, что бы они были актуальны. Ну и еще закрываю потому, что в этом уже нет смысла
