### ISSUE TITLE
Удаление людей новым drag'n'drop'ом в body analyzer

### ISSUE THREAD

**Issue by DieSiege** [GammaStation/Gamma-Station#60]
#### Подробное описание проблемы
Перепил боди аналайзера позволил удалять людей из континуума. Достать их можно только педальным телепортом. Иначе никак.
#### Что должно было произойти
Человек засунут в сканер и больше людей запихивать в него нельзя
#### Что произошло на самом деле
Человек засунут в сканер и тем не менее их можно продолжать в него засовывать
#### Как повторить
Засунуть сначала человека как обычно grab'ом, а потом начать в него засовывать людей drag'n'drop'ом. Можно и наоборот.
#### Дополнительная информация:
Well, fuck. Чо, пацаны. Прячем так диск от нюки?

**Comment by AgRevol** [comment]
https://i.gyazo.com/6249433c990607af29659dc9ee67482c.mp4
Такую легендарную фичу проебали
