### ISSUE TITLE
Сломаны слоты брони, разгрузки и т.д.

### ISSUE THREAD

**Issue by Lizurt** [GammaStation/Gamma-Station#609]
#### Подробное описание проблемы
Слоты(карманы) большинства брони сломаны и не дают всунуть предмет в себя любого размера, даже крохотного. В логах ничего не выводится, вещи просто не ложатся.
#### Что должно было произойти
В карман должна поместится малая или крохотная вещь
#### Что произошло на самом деле
Ничего не происходит, предмет не ложится в кармашек
#### Как повторить
Кликнуть малым или крохотным предметом по броне
#### Дополнительная информация:
LOOC: Hans (Good314): Тоже карманы не работают
LOOC: Elias Ringer (EllonCake): я в куртку криминалиста пытался вещь положить, но не получалось
LOOC: Hans (Good314): Разгрузка тоже не работает

**Comment by LudwigVonChesterfield** [comment]
![image](https://user-images.githubusercontent.com/17705613/49748096-7f4b8e80-fcad-11e8-85cf-14469b5cf837.png)

**Comment by Lizurt** [comment]
Это халат генетика, я говорил про обычный. Хочу еще добавить, что он не работает как "бронежилет", в слот для брони нельзя положить мелкий предмет.

**Comment by LudwigVonChesterfield** [comment]
1) в слот для брони халата кладутся только определённые вещи(светоручка)
2) я тестил и в обычном лабораторном халате - всё так же, ты чего-то недоговариваешь.

**Comment by Lizurt** [comment]
Не знаю. Насчет слота брони - проверил только что. Те вещи, которые раньше туда ложились уже не ложатся, но другие - все еще да. Так что я был не прав насчет него, да. Но в карман все еще не могу положить, даже ту же ручку. Это не может быть особенностью расы? Просто я сейчас не за человека, мало ли
UPD: проверено прямо в игре другими людьми LOOC: Hans (Good314): Тоже карманы не работают 
LOOC: Elias Ringer (EllonCake): я в куртку криминалиста пытался вещь положить, но не получалось

и еще инфа: LOOC: Hans (Good314): Разгрузка тоже не работает
вывод: все слоты брони сломаны

**Comment by Popug** [comment]
Я в olive jacket не могу ложить предметы
