### ISSUE TITLE
Помимо карманов, ещё и очки у ОБР 

### ISSUE THREAD

**Issue by Popug** [GammaStation/Gamma-Station#613]
## Подробное описание проблемы
Одежда ОБР (у лидера, как минимум) похерена.

#### Что должно было произойти
Сангласис видимы, их можно снять, вещи ложатся в разгрузку и ремень.

#### Что произошло на самом деле
Спрайт солнцезащитных очков невидим в интерфейсе и их нельзя снять, вещи не ложатся в разгрузку и ремень.

#### Как повторить
Зайти за ЕРТ, убедиться, что на вас надеты невидимые солнечные очки, которые нельзя снять, попытаться засунуть вещи в ремень и разгрузку.

#### Дополнительная информация:
То же самое с халатами, куртками, бронежилетами и тд - карманы не работают.

**Comment by Popug** [comment]
Хоть и хотфикснули слоты, но очки надо проверить

**Comment by SanecMan** [comment]
Идёт чистка говноспрайтов, please walt..........
