### ISSUE TITLE
В себя уже не спрячешь  

### ISSUE THREAD

**Issue by Mintt69** [GammaStation/Gamma-Station#618]
#### Подробное описание проблемы
Compressed Implant сломаны
#### Что должно было произойти
Должен был появится дополнительный карман
#### Что произошло на самом деле
ничего
#### Как повторить
ввести Compressed Implant

**Comment by SanecMan** [comment]
Видимо во всём виновна Action_button **Д**_Е_**Л**_Ю_**К**_С_, нужен фикс
