### ISSUE TITLE
Тихеон можно убить кидая в неё предметы

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#619]
#### Подробное описание проблемы
Тихеон нельзя хуярить с харма
но
Можно захуярить если бросать в неё предметы

#### Что должно было произойти
_MISS_

#### Что произошло на самом деле
Харм харм харм ГИБ ТИХЕОНКИ всё

#### Как повторить
Кидать в тихеона предметы

#### Дополнительная информация:
![image](https://user-images.githubusercontent.com/36476150/50041765-b692b480-008c-11e9-93be-bbaa61f14ecb.png)

**Comment by SanecMan** [comment]
https://ttm.sh/PK.mp4

**Comment by LudwigVonChesterfield** [comment]
ложь и провокация, у них шанс на попадание в них предмета такой же как удар с харма.

**Comment by SanecMan** [comment]
Я так понял что я послушал дебика и в итоге остался в говне. Ёбаный стыд.

**Comment by blind0** [comment]
> Я так понял что я послушал дебика и в итоге остался в говне. Ёбаный стыд.

незашто
