### ISSUE TITLE
Для учёного скафандра акшон битттон проебали

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#623]
#### Подробное описание проблемы
Смотрим описание ишью сверху.

#### Что должно было произойти
Должна быть кнопка закрытия стекла на шлеме учёного скафандра

#### Что произошло на самом деле
![image](https://user-images.githubusercontent.com/36476150/50043707-a8a05c00-00ab-11e9-8133-76c888dfd322.png)

![image](https://user-images.githubusercontent.com/36476150/50043708-ae963d00-00ab-11e9-9bce-d82ec7c206c4.png)

#### Как повторить
Одеваем скафандр со стеклом закрывающемся. Всё.

**Comment by SanecMan** [comment]
Дополнил ишью

**Comment by Filatelele** [comment]
Вроде как пофиксил это, без понятия почему ишью все еще висит.
