### ISSUE TITLE
Цвет крови - красный

### ISSUE THREAD

**Issue by SanecMan** [GammaStation/Gamma-Station#639]
#### Подробное описание проблемы
Отстрелите голову скреллу и вы получите КРАСНУЮ кровь

![image](https://user-images.githubusercontent.com/36476150/50266670-1c998600-0457-11e9-9579-2b650875243d.png)

#### Что должно было произойти
Фиолетовая кровь

#### Что произошло на самом деле
Красная кровь

#### Как повторить
Отстрелить голову скреллу

**Comment by omejka** [comment]
Это не кровь а дамаг оверлей
(или хаск)

**Comment by Moggilazz** [comment]
Это не баг. На скрине мы видим труп без скафандра в космосе, которому накинуло бёрнурона до состояния хаска

**Comment by SanecMan** [comment]
Отстреливаем голову кукле (да пусть в космосе) и наблюдаем что там текстура красная
