### ISSUE TITLE
Охладительная система не работает на СПУ

### ISSUE THREAD

**Issue by MrFoxik** [GammaStation/Gamma-Station#64]
#### Подробное описание проблемы
Я одел скафандр, одел и включил охладительную систему. Получал нагрев.
#### Что должно было произойти
Нагрев должен убавляться или не возникать.
#### Что произошло на самом деле
Я нагревался.
#### Как повторить
Одеть скафандр, включить охладительную систему за СПУ, наслаждаться теплом.
#### Дополнительная информация:
Это анальная боль.

**Comment by AgRevol** [comment]
Всё работает нормально, буквально вчера использовал её

**Comment by MrFoxik** [comment]
Сегодня использовал, и не мог охладится, в итоге жил на ремонте с помощью проводов. Возможно, я не мог охладиться потому что уже нагрелся, и оно просто поддерживало этот уровень температуры, не понижая его.

**Comment by Olt1771** [comment]
Всё работает, только в Suit_storage а не на спине. Можно закрывать

**Comment by Miracler112** [comment]
Ишью закрываю, так как не баг
