### ISSUE TITLE
Что-то стрёмное в Miscellaneous Research

### ISSUE THREAD

**Issue by Pivo24** [GammaStation/Gamma-Station#668]
#### Подробное описание проблемы
Я не знаю как это описать, я просто летал за госта пока не встретил это.
#### Что должно было произойти
Не это.
#### Что произошло на самом деле
Это: 
![wut](https://user-images.githubusercontent.com/42682553/52521954-2e95e900-2c90-11e9-822a-135735be2add.png)

#### Как повторить
Не знаю, просто полетал за госта.
#### Дополнительная информация:
При наведении курсора на это... Чем бы это ни было, отображает как floor.

**Comment by Armando-Rodriguez17** [comment]
Это не баг, просто педали охуели. Такое только для гостов. После рестарта пропадет

**Comment by Filatelele** [comment]
Происки вражеских агентов, оставайтесь на месте, мы с вами свяжемся.
