### ISSUE TITLE
Нюка палится по синдиборгам и пда, которые спавнятся в начале нюки

### ISSUE THREAD

**Issue by Kernstall** [GammaStation/Gamma-Station#75]
#### Подробное описание проблемы
Нюка палится по синдиборгам и пда, которые спавнятся в начале нюки
#### Что должно было произойти
Нюка не палится по синдиборгам и пда, которые спавнятся в начале нюки
#### Что произошло на самом деле
Нюка палится по синдиборгам и пда, которые спавнятся в начале нюки
#### Как повторить
Форсанють нюку и посмотреть список пда/синдиборгов

**Comment by Skippeer12** [comment]
ПДА не должны палится, там затычка. А вон на счёт боргов, это уже можно считать фичей, потому что борг может отключить ПДА месседжер и его будет не возможно спалить.

**Comment by Kernstall** [comment]
Надо проверить, потому что недавно была жалоба на пии, который палил нюку по пда

**Comment by Skippeer12** [comment]
>жалоба на пии

C этого надо было и начинать. пИИ видит все ПДА, не важно где они.

**Comment by Kernstall** [comment]
> C этого надо было и начинать. пИИ видит все ПДА, не важно где они.

Это ли не баг?
