### ISSUE TITLE
смерть дионы в  Man-Machine Interface.

### ISSUE THREAD

**Issue by vay534** [GammaStation/Gamma-Station#88]
#### Подробное описание проблемы
если диону сунуть (или она сама залезет ) в   Man-Machine Interface то она умирает и с её помощью нельзя создать борга или ии
#### Что должно было произойти
диона должна жить и её можно использовать в ии и боргах
#### Что произошло на самом деле
как только диона попала в   Man-Machine Interface она умерла 
#### Как повторить
засунуть (или залезть) в Man-Machine Interface.

**Comment by Moggilazz** [comment]
Должно быть исправлено после #306
