### ISSUE TITLE
Сломанные мед-худы

### ISSUE THREAD

**Issue by AgRevol** [GammaStation/Gamma-Station#90]
#### Подробное описание проблемы
Медхуды не отображают настоящее состояние пациента
#### Что должно было произойти
С помощью медхудов можно спокойно смотреть примерное хп пациента
#### Что произошло на самом деле
Живые люди имеют крит/мертвое состояние, мертвые обезглавленные имеют фул хп. 
#### Как повторить
Поиграть на медике с мед худами
#### Дополнительная информация:
Судя по всему оно в определенный 
момент застряет в одном положении и далее уже не меняется.
![35f308047e18d88101ee0c6f5c142e8b](https://user-images.githubusercontent.com/29666964/43371767-2f8fc0b6-93a1-11e8-8b3c-ebc88150266e.png)
![88bfcc3178938701a8c14586f1b54048](https://user-images.githubusercontent.com/29666964/43371772-39c3bdd0-93a1-11e8-9610-a39c75004fd7.png)
![f3b62fb6752f8177978ffc13eda26ab7](https://user-images.githubusercontent.com/29666964/43371775-3c506a76-93a1-11e8-9133-31c03771e9d8.png)
![c930993e5e9d45ee8632a99b10d0c46a](https://user-images.githubusercontent.com/29666964/43371770-382fb5b4-93a1-11e8-85e7-ea60f7fb9ed6.png)

**Comment by DieSiege** [comment]
#77
