### ISSUE TITLE
Danger, Danger, Danger! Woo Hoo!

### ISSUE THREAD

**Issue by WatlerJe** [GammaStation/Gamma-Station#94]
#### Подробное описание проблемы
Будучи голым карликом попытался разбить ГОЛЫМИ РУКАМИ стойку с капитанским лазуром, после каждого удара выдавало следующее:
https://i.gyazo.com/fe72c58e21f1390fc7292a20d4351162.png
#### Что должно было произойти
Явно не это. Подозреваю, что во всем виноваты коготки.
#### Что произошло на самом деле
Danger danger
#### Как повторить
HIGHT VOLTAGE!
#### Дополнительная информация:
It's my desire, it's my desire, it's my desire!

**Comment by AgRevol** [comment]
Относительно старый баг к слову, который никто не зарепортил. Это вообще при любой атаке происходит, если не ошибаюсь (Либо только при атаке кулачками, но при этом точно любая раса)
